# Generated by Django 3.1.7 on 2021-04-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='Name',
            new_name='name',
        ),
    ]
