# Generated by Django 3.1.7 on 2021-04-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210424_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bands',
            field=models.ManyToManyField(to='myapi.Band'),
        ),
        migrations.AddField(
            model_name='song',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
    ]
