# Generated by Django 3.1.7 on 2021-04-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210424_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
